FROM vrodriguezf/rstudio-server-shiny-development:latest

# Install R packages
RUN R -e "install.packages(c('dygraphs', 'shinycssloaders'))"

ENV RETICULATE_MINICONDA_PATH=/usr/local/share/r-miniconda
RUN R -e "reticulate::install_miniconda()"

RUN R -e "reticulate::py_install(c('pandas','wandb','hdbscan'), pip = TRUE, pip_options=c('--upgrade'))"
