# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tchub/',
                'doc_host': 'https://vrodriguezf.github.io',
                'git_url': 'https://gitlab.geist.re/pml/x_timecluster_extension/tree/master/',
                'lib_path': 'dvats'},
  'syms': { 'dvats.all': {},
            'dvats.dr': {},
            'dvats.encoder': {},
            'dvats.imports': {},
            'dvats.load': {},
            'dvats.utils': {},
            'dvats.visualization': {}}}