# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dvats/',
                'doc_host': 'https://vrodriguezf.github.io',
                'git_url': 'https://github.com/vrodriguezf/deepvats',
                'lib_path': 'dvats'},
  'syms': {'dvats.all': {}, 'dvats.dr': {}, 'dvats.imports': {}, 'dvats.load': {}, 'dvats.utils': {}, 'dvats.visualization': {}}}