# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/memory.ipynb.

# %% auto 0
__all__ = ['memMB2GB', 'memb2GB', 'get_decoded_memory', 'get_gpu_memory', 'color_for_percentage', 'create_bar',
           'gpu_memory_status', 'get_cpu_memory', 'cpu_memory_status']

# %% ../nbs/memory.ipynb 2
import subprocess
import psutil
import tsai.imports as ts

# %% ../nbs/memory.ipynb 4
def memMB2GB( mem : int) -> int: 
    return int(round(mem/1024, 2))
def memb2GB( mem : int) -> int: 
    return int(round(mem/1024**3, 2))

# %% ../nbs/memory.ipynb 5
def get_decoded_memory(used_total = "used", device = None, verbose = 0):
    if verbose > 0: print("Get " + used_total + " memory information")
    if device is None:
        if verbose > 0: print("For all GPUs devices")
        mem_info = subprocess.check_output(["nvidia-smi", "--query-gpu=memory."+used_total, "--format=csv"]).decode("ascii").split("\n")[:-1][1:]
        if verbose > 0: print("Memory info: ", mem_info)
        mem_values = [int(x.split()[0]) for x in mem_info]
        if verbose > 0: print("Memory values: ", mem_values)
        return mem_values
    else:
        if verbose > 0: print("For device", device)
        return int(subprocess.check_output(["nvidia-smi", "--query-gpu=memory."+used_total, "--format=csv,noheader,nounits", "--id=" + str(device)]).decode("ascii").split("\n")[0])
    
def get_gpu_memory(
    device : int = 0, 
    all : bool = False, 
    verbose: int = 0
):    
    if all:
        if verbose > 0: print("all")
        total_memory = ts.get_gpu_memory()
        if verbose > 0: print("--> Get ussed memory info")
        used_memory = get_decoded_memory("used", None, verbose)
        used_memory = [memMB2GB(x) for x in used_memory]
        if verbose > 0: print("--> Compute array of percentages")
        percentage = [ round((x / y) * 100) for (x, y) in zip(used_memory, total_memory) ]
    else:
        if verbose > 0: print("one: device ", device)
        total_memory = memMB2GB( get_decoded_memory("total", device) )
        used_memory  = memMB2GB( get_decoded_memory("used", device) )
        percentage = round((used_memory / total_memory) * 100)

    if verbose > 0: print("Total ", total_memory, " | Used ", used_memory, " | Percentage ", percentage)
    
    return used_memory, total_memory, percentage

# %% ../nbs/memory.ipynb 7
def color_for_percentage(percentage):
    if percentage < 20:
        return "\033[90m"  # Gray
    elif percentage < 40:
        return "\033[94m"  # Blue
    elif percentage < 60:
        return "\033[92m"  # Green
    elif percentage < 80:
        return "\033[93m"  # Orange
    else:
        return "\033[91m"  # Red

# %% ../nbs/memory.ipynb 8
def create_bar(percentage, color_code, length=20):
    filled_length = int(length * percentage // 100)
    bar = "█" * filled_length + "-" * (length - filled_length)
    return color_code + bar + "\033[0m"  # Apply color and reset after bar

# %% ../nbs/memory.ipynb 9
def gpu_memory_status(device=0):
    used, total, percentage = get_gpu_memory(device)
    color_code = color_for_percentage(percentage)
    bar = create_bar(percentage, color_code)
    print(f"GPU | Used mem: {used}")
    print(f"GPU | Used mem: {total}")
    print(f"GPU | Memory Usage: [{bar}] {color_code}{percentage}%\033[0m")

# %% ../nbs/memory.ipynb 11
def get_cpu_memory():
    mem = psutil.virtual_memory()
    total_memory = memb2GB(mem.total)
    used_memory = memb2GB(mem.total - mem.available)
    percentage = mem.percent
    return used_memory, total_memory, percentage

# %% ../nbs/memory.ipynb 13
def cpu_memory_status():
    used, total, percentage = get_cpu_memory()
    color_code = color_for_percentage(percentage)
    bar = create_bar(percentage, color_code)
    print(f"CPU | Used mem: {used}")
    print(f"CPU | Used mem: {total}")
    print(f"CPU | Memory Usage: [{bar}] {color_code}{percentage}%\033[0m")
