# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/memory.ipynb.

# %% auto 0
__all__ = ['get_gpu_memory', 'color_for_percentage', 'create_bar', 'gpu_memory_status', 'get_cpu_memory', 'cpu_memory_status']

# %% ../nbs/memory.ipynb 2
import subprocess
import psutil
import tsai.imports as ts

# %% ../nbs/memory.ipynb 4
def get_gpu_memory(device=0):
    total_memory = subprocess.check_output(["nvidia-smi", "--query-gpu=memory.total", "--format=csv,noheader,nounits", "--id=" + str(device)])
    total_memory = int(total_memory.decode().split('\n')[0])
    used_memory = subprocess.check_output(["nvidia-smi", "--query-gpu=memory.used", "--format=csv,noheader,nounits",  "--id=" + str(device)])
    used_memory = int(used_memory.decode().split('\n')[0])

    percentage = round((used_memory / total_memory) * 100)
    return used_memory, total_memory, percentage

# %% ../nbs/memory.ipynb 5
def color_for_percentage(percentage):
    if percentage < 20:
        return "\033[90m"  # Gray
    elif percentage < 40:
        return "\033[94m"  # Blue
    elif percentage < 60:
        return "\033[92m"  # Green
    elif percentage < 80:
        return "\033[93m"  # Orange
    else:
        return "\033[91m"  # Red

# %% ../nbs/memory.ipynb 6
def create_bar(percentage, color_code, length=20):
    filled_length = int(length * percentage // 100)
    bar = "█" * filled_length + "-" * (length - filled_length)
    return color_code + bar + "\033[0m"  # Apply color and reset after bar

# %% ../nbs/memory.ipynb 7
def gpu_memory_status(device=0):
    used, total, percentage = get_gpu_memory(device)
    color_code = color_for_percentage(percentage)
    bar = create_bar(percentage, color_code)
    print(f"GPU | Used mem: {used}")
    print(f"GPU | Used mem: {total}")
    print(f"GPU | Memory Usage: [{bar}] {color_code}{percentage}%\033[0m")

# %% ../nbs/memory.ipynb 11
def get_cpu_memory():
    mem = psutil.virtual_memory()
    total_memory = mem.total // (1024**2)  # Convertir a MB
    used_memory = (mem.total - mem.available) // (1024**2)  # Convertir a MB
    percentage = mem.percent
    return used_memory, total_memory, percentage

# %% ../nbs/memory.ipynb 12
def cpu_memory_status():
    used, total, percentage = get_cpu_memory()
    color_code = color_for_percentage(percentage)
    bar = create_bar(percentage, color_code)
    print(f"CPU | Used mem: {used}")
    print(f"CPU | Used mem: {total}")
    print(f"CPU | Memory Usage: [{bar}] {color_code}{percentage}%\033[0m")
