# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"df_slicer": "02_DCAE.ipynb",
         "createDCAE": "02_DCAE.ipynb",
         "check_compatibility": "03_dimensionality_reduction.ipynb",
         "normalize_dr_artifact": "03_dimensionality_reduction.ipynb",
         "get_latent_features": "03_dimensionality_reduction.ipynb",
         "fget_UMAP_embeddings": "03_dimensionality_reduction.ipynb",
         "plot_embeddings": "03_dimensionality_reduction.ipynb",
         "fpreprocess_numeric_vars": "load.ipynb",
         "fread_and_concat": "load.ipynb",
         "fread_mining_monitoring_files": "load.ipynb",
         "TSArtifact": "load.ipynb",
         "wandb.apis.public.Artifact.to_df": "load.ipynb",
         "wandb.apis.public.Artifact.to_tsartifact": "load.ipynb",
         "create_longwall_data_artifact": "load.ipynb",
         "load_longwall_data_artifact": "load.ipynb",
         "generate_TS_df": "utils.ipynb",
         "normalize_columns": "utils.ipynb",
         "remove_constant_columns": "utils.ipynb",
         "ReferenceArtifact": "utils.ipynb",
         "wandb.apis.public.Artifact.to_obj": "utils.ipynb",
         "plot_TS": "visualization.ipynb"}

modules = ["dcae.py",
           "utils.py",
           "dr.py",
           "load.py",
           "visualization.py"]

doc_url = "https://vrodriguezf.github.io/timecluster_extension/"

git_url = "https://gitlab.geist.re/pml/x_timecluster_extension/tree/master/"

def custom_doc_links(name): return None
