# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/visualization.ipynb (unless otherwise specified).

__all__ = ['plot_TS']

# Cell
from fastcore.all import *
import pandas as pd
import numpy as np

# Cell
@delegates(pd.DataFrame.plot)
def plot_TS(df:pd.core.frame.DataFrame, **kwargs):
    df.plot(subplots=True, **kwargs)
    plt.show()