# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fpreprocess_numeric_vars": "00_load.ipynb",
         "fread_and_concat": "00_load.ipynb",
         "fread_mining_monitoring_files": "00_load.ipynb",
         "TSArtifact": "00_load.ipynb",
         "wandb.apis.public.Artifact.to_df": "00_load.ipynb",
         "wandb.apis.public.Artifact.to_tsartifact": "00_load.ipynb",
         "create_longwall_data_artifact": "00_load.ipynb",
         "load_longwall_data_artifact": "00_load.ipynb",
         "generate_TS_df": "01_utils.ipynb",
         "normalize_columns": "01_utils.ipynb",
         "remove_constant_columns": "01_utils.ipynb",
         "ReferenceArtifact": "01_utils.ipynb",
         "wandb.apis.public.Artifact.to_obj": "01_utils.ipynb",
         "df_slicer": "02_DCAE.ipynb",
         "createDCAE": "02_DCAE.ipynb",
         "check_compatibility": "03_dimensionality_reduction.ipynb",
         "get_latent_features": "03_dimensionality_reduction.ipynb",
         "fget_UMAP_embeddings": "03_dimensionality_reduction.ipynb",
         "plot_embeddings": "03_dimensionality_reduction.ipynb",
         "plot_TS": "04_visualization.ipynb"}

modules = ["load.py",
           "utils.py",
           "dcae.py",
           "dr.py",
           "visualization.py"]

doc_url = "https://vrodriguezf.github.io/pacmel_mining_use_case/"

git_url = "https://gitlab.geist.re/pml/x_timecluster_extension/tree/master/"

def custom_doc_links(name): return None
