# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_numeric_vars": "00_load.ipynb",
         "fslicer": "01_Timecluster_replication.ipynb",
         "createDCAE": "01_Timecluster_replication.ipynb",
         "slices2array": "01_Timecluster_replication.ipynb",
         "train_surrogate_model": "01_Timecluster_replication.ipynb"}

modules = ["load.py",
           "timecluster.py"]

doc_url = "https://vrodriguezf.github.io/pacmel_mining_use_case/"

git_url = "https://github.com/vrodriguezf/pacmel_mining_use_case/tree/master/"

def custom_doc_links(name): return None
