# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"infer_or_inject_freq": "01_dataset_artifact.ipynb",
         "DCAE_torch": "02a_encoder_DCAE-torch.ipynb",
         "check_compatibility": "03_dimensionality_reduction.ipynb",
         "fget_UMAP_projections": "03_dimensionality_reduction.ipynb",
         "plot_projections": "03_dimensionality_reduction.ipynb",
         "TSArtifact": "load.ipynb",
         "wandb.apis.public.Artifact.to_df": "load.ipynb",
         "wandb.apis.public.Artifact.to_tsartifact": "load.ipynb",
         "generate_TS_df": "utils.ipynb",
         "normalize_columns": "utils.ipynb",
         "remove_constant_columns": "utils.ipynb",
         "ReferenceArtifact": "utils.ipynb",
         "wandb.apis.public.Artifact.to_obj": "utils.ipynb",
         "PrintLayer": "utils.ipynb",
         "Learner.export_and_get": "utils.ipynb",
         "plot_TS": "visualization.ipynb",
         "plot_validation_ts_ae": "visualization.ipynb"}

modules = ["data.py",
           "dcae.py",
           "dr.py",
           "load.py",
           "utils.py",
           "visualization.py"]

doc_url = "https://vrodriguezf.github.io/tchub/"

git_url = "https://gitlab.geist.re/pml/x_timecluster_extension/tree/master/"

def custom_doc_links(name): return None
