# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/core.ipynb (unless otherwise specified).

__all__ = ['ENCODER_EMBS_MODULE_NAME']

# Cell
from tsai.models.all import *
from .dcae import DCAE_torch

# Cell
ENCODER_EMBS_MODULE_NAME = {
    InceptionTimePlus: 'backbone', # for mvp based models
    DCAE_torch: 'bottleneck.latent_in'
}