# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_dataset_artifact.ipynb (unless otherwise specified).

__all__ = ['infer_or_inject_freq']

# Cell
def infer_or_inject_freq(df, injected_freq='1s'):
    """
        Infer index frequency. If there's not a proper time index, create fake timestamps,
        keeping the desired `injected_freq`. If that is None, set a default one of 1 second
    """
    inferred_freq = pd.infer_freq(df.index)
    if inferred_freq == 'N':
        timedelta = pd.to_timedelta(injected_freq)
        df.index = pd.to_datetime(0) + timedelta*df.index
        df.index.freq = injected_freq
    else:
        df.index.freq = inferred_freq
    return df